---
# Source: digitalhub/templates/argo-s3-secret.yaml
# SPDX-FileCopyrightText: Â© 2025 DSLab - Fondazione Bruno Kessler
#
# SPDX-License-Identifier: AGPL-3.0-or-later

apiVersion: v1
data:
  accesskey: YXJnbw==
  secretkey: YXJnbzEyMzQ=
kind: Secret
metadata:
  name: argo-s3-creds
type: Opaque
