---
# Source: digitalhub/templates/core-postgresql-cluster.yaml
# SPDX-FileCopyrightText: Â© 2025 DSLab - Fondazione Bruno Kessler
#
# SPDX-License-Identifier: AGPL-3.0-or-later

apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: core-postgres-cluster
spec:
  teamId: "core"
  volume:
    size: 8Gi
  numberOfInstances: 1
  users:
    coreadmin:  # database owner
    - superuser
    - createdb
    coreuser: []
  databases:
    core: coreuser
  postgresql:
    version: "15"
  resources:
    limits:
      cpu: "2"
      memory: 2Gi
    requests:
      cpu: 512m
      memory: 1000Mi
