---
# Source: digitalhub/templates/seaweed-secret.yaml
# SPDX-FileCopyrightText: Â© 2025 DSLab - Fondazione Bruno Kessler
#
# SPDX-License-Identifier: AGPL-3.0-or-later

apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: seaweed-s3-secret
stringData:
  # this key must be an inline json config file
  seaweedfs_s3_config: '{"identities":[{"name":"rootuser","credentials":[{"accessKey":"rootuser","secretKey":"rootpassword"}],"actions":["Admin","Read","Write"]},{"name":"digitalhub","credentials":[{"accessKey":"digitalhub","secretKey":"digitalhub"}],"actions":["Read:datalake","Write:datalake"]},{"name":"argo","credentials":[{"accessKey":"argo","secretKey":"argo1234"}],"actions":["Read:argo","Write:argo"]}]}'
