---
# Source: digitalhub/charts/docker-registry/templates/pvc.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: digitalhub-docker-registry
  namespace: default
  labels:
    app: digitalhub-docker-registry
    chart: "docker-registry-2.3.0"
    release: "digitalhub"
    heritage: "Helm"
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "128Gi"
