---
# Source: digitalhub/charts/docker-registry/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: digitalhub-docker-registry-secret
  namespace: default
  labels:
    app: docker-registry
    chart: docker-registry-2.3.0
    heritage: Helm
    release: digitalhub
type: Opaque
data:
  haSharedSecret: "aVZINHNNanMxZHI2bnpJRw=="
  proxyUsername: ""
  proxyPassword: ""
