---
# Source: digitalhub/templates/template-controller/rbac.yaml
# SPDX-FileCopyrightText: Â© 2025 DSLab - Fondazione Bruno Kessler
#
# SPDX-License-Identifier: AGPL-3.0-or-later

apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-transformer
---
# Source: digitalhub/templates/template-controller/rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: configmap-transformer
---
# Source: digitalhub/templates/template-controller/rbac.yaml
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: secret-transformer
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["*"]
---
# Source: digitalhub/templates/template-controller/rbac.yaml
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: configmap-transformer
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["*"]
---
# Source: digitalhub/templates/template-controller/rbac.yaml
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: secret-transformer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: secret-transformer
subjects:
  - kind: ServiceAccount
    name: secret-transformer
    namespace: default
---
# Source: digitalhub/templates/template-controller/rbac.yaml
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: configmap-transformer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: configmap-transformer
subjects:
  - kind: ServiceAccount
    name: configmap-transformer
    namespace: default
