---
# Source: digitalhub/charts/postgres-operator/templates/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: digitalhub-postgres-operator
  labels:
    app.kubernetes.io/name: postgres-operator
    helm.sh/chart: postgres-operator-1.11.0
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: digitalhub
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: digitalhub-postgres-operator
subjects:
- kind: ServiceAccount
  name: digitalhub-postgres-operator
  namespace: default
