---
# Source: digitalhub/charts/postgres-operator/templates/postgres-pod-priority-class.yaml
apiVersion: scheduling.k8s.io/v1
description: 'Use only for databases controlled by Postgres operator'
kind: PriorityClass
metadata:
  labels:
    app.kubernetes.io/name: postgres-operator
    helm.sh/chart: postgres-operator-1.11.0
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: digitalhub
  name: digitalhub-postgres-operator-pod
  namespace: default
preemptionPolicy: PreemptLowerPriority
globalDefault: false
value: 1e+06
