---
# Source: digitalhub/charts/postgres-operator/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: digitalhub-postgres-operator
  namespace: default
  labels:
    app.kubernetes.io/name: postgres-operator
    helm.sh/chart: postgres-operator-1.11.0
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: digitalhub
