---
# Source: digitalhub/charts/postgres-operator/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: postgres-operator
    helm.sh/chart: postgres-operator-1.11.0
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: digitalhub
  name: digitalhub-postgres-operator
  namespace: default
spec:
  type: ClusterIP
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: digitalhub
    app.kubernetes.io/name: postgres-operator
