---
# Source: digitalhub/charts/seaweedfs/templates/cluster-role.yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: seaweedfs-rw-cr
  labels:
    app.kubernetes.io/name: seaweedfs
    helm.sh/chart: seaweedfs-4.0.393
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: digitalhub
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
# Source: digitalhub/charts/seaweedfs/templates/cluster-role.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: system:serviceaccount:seaweedfs:default
  labels:
    app.kubernetes.io/name: seaweedfs
    helm.sh/chart: seaweedfs-4.0.393
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: digitalhub
subjects:
  - kind: ServiceAccount
    name: seaweedfs
    namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: seaweedfs-rw-cr
---
# Source: digitalhub/charts/seaweedfs/templates/cluster-role.yaml
#hack for delete pod master after migration
