---
# Source: digitalhub/charts/seaweedfs/templates/filer-service-client.yaml
apiVersion: v1
kind: Service
metadata:
  name: seaweedfs-filer-client
  namespace: default
  labels:
    app.kubernetes.io/name: seaweedfs
    helm.sh/chart: seaweedfs-4.0.393
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: digitalhub
    app.kubernetes.io/component: filer
    monitoring: "true"
spec:
  clusterIP: None
  ports:
  - name: "swfs-filer"
    port: 8888
    targetPort: 8888
    protocol: TCP
  - name: "swfs-filer-grpc"
    port: 18888
    targetPort: 18888
    protocol: TCP
  - name: "metrics"
    port: 9327
    targetPort: 9327
    protocol: TCP
  selector:
    app.kubernetes.io/name: seaweedfs
    app.kubernetes.io/component: filer
