---
# Source: digitalhub/charts/seaweedfs/templates/master-statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: seaweedfs-master
  namespace: default
  labels:
    app.kubernetes.io/name: seaweedfs
    helm.sh/chart: seaweedfs-4.0.393
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: digitalhub
    app.kubernetes.io/component: master
spec:
  serviceName: seaweedfs-master
  podManagementPolicy: Parallel
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: seaweedfs
      app.kubernetes.io/instance: digitalhub
      app.kubernetes.io/component: master
  template:
    metadata:
      labels:
        app.kubernetes.io/name: seaweedfs
        helm.sh/chart: seaweedfs-4.0.393
        app.kubernetes.io/instance: digitalhub
        app.kubernetes.io/component: master
      
      annotations:
      
    spec:
      restartPolicy: Always
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app.kubernetes.io/name: seaweedfs
                  app.kubernetes.io/instance: digitalhub
                  app.kubernetes.io/component: master
              topologyKey: kubernetes.io/hostname
      
      terminationGracePeriodSeconds: 60
      enableServiceLinks: false
      serviceAccountName: "seaweedfs" # for deleting statefulset pods after migration
      containers:
        - name: seaweedfs
          image: chrislusf/seaweedfs:3.93
          imagePullPolicy: IfNotPresent
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: SEAWEEDFS_FULLNAME
              value: "seaweedfs"
            - name: WEED_MASTER_VOLUME_GROWTH_COPY_1
              value: "7"
            - name: WEED_MASTER_VOLUME_GROWTH_COPY_2
              value: "6"
            - name: WEED_MASTER_VOLUME_GROWTH_COPY_3
              value: "3"
            - name: WEED_MASTER_VOLUME_GROWTH_COPY_OTHER
              value: "1"
            - name: WEED_CLUSTER_DEFAULT
              value: "sw"
            - name: WEED_CLUSTER_SW_FILER
              value: "seaweedfs-filer-client.seaweedfs:8888"
            - name: WEED_CLUSTER_SW_MASTER
              value: "seaweedfs-master.seaweedfs:9333"
          command:
            - "/bin/sh"
            - "-ec"
            - |
              exec /usr/bin/weed \
              -logdir=/logs \
              -v=1 \
              master \
              -port=9333 \
              -mdir=/data \
              -ip.bind=0.0.0.0 \
              -defaultReplication=000 \
              -metricsPort=9327 \
              -volumeSizeLimitMB=1000 \
              -electionTimeout=10s \
              -heartbeatInterval=300ms \
              -ip=${POD_NAME}.${SEAWEEDFS_FULLNAME}-master.default \
              -peers=${SEAWEEDFS_FULLNAME}-master-0.${SEAWEEDFS_FULLNAME}-master.default:9333 \
          volumeMounts:
            - name : data-default
              mountPath: /data
            - name: seaweedfs-master-log-volume
              mountPath: "/logs/"
            - name: master-config
              readOnly: true
              mountPath: /etc/seaweedfs/master.toml
              subPath: master.toml
            
          ports:
            - containerPort: 9333
              name: swfs-master
            - containerPort: 19333
              #name: swfs-master-grpc
          readinessProbe:
            httpGet:
              path: /cluster/status
              port: 9333
              scheme: 
            initialDelaySeconds: 10
            periodSeconds: 45
            successThreshold: 2
            failureThreshold: 100
            timeoutSeconds: 10
          livenessProbe:
            httpGet:
              path: /cluster/status
              port: 9333
              scheme: 
            initialDelaySeconds: 20
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 4
            timeoutSeconds: 10
      volumes:
        - name: seaweedfs-master-log-volume
          hostPath:
            path: /storage/logs/seaweedfs/master
            type: DirectoryOrCreate
        - name: data-default
          hostPath:
            path: /ssd/seaweed-master/
            type: DirectoryOrCreate
        - name: master-config
          configMap:
            name: seaweedfs-master-config
        
      nodeSelector:
        kubernetes.io/arch: amd64
