---
# Source: digitalhub/charts/seaweedfs/templates/master-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: seaweedfs-master
  namespace: default
  labels:
    app.kubernetes.io/name: seaweedfs
    app.kubernetes.io/component: master
    helm.sh/chart: seaweedfs-4.0.393
    app.kubernetes.io/managed-by: Helm
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
  - name: "swfs-master"
    port: 9333
    targetPort: 9333
    protocol: TCP
  - name: "swfs-master-grpc"
    port: 19333
    targetPort: 19333
    protocol: TCP
  - name: "metrics"
    port: 9327
    targetPort: 9327
    protocol: TCP
  selector:
    app.kubernetes.io/name: seaweedfs
    app.kubernetes.io/component: master
