---
# Source: digitalhub/charts/seaweedfs/templates/master-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: seaweedfs-master-config
  namespace: default
  labels:
    app.kubernetes.io/name: seaweedfs
    helm.sh/chart: seaweedfs-4.0.393
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: digitalhub
data:
  master.toml: |-
    
    # Enter any extra configuration for master.toml here.
    # It may be a multi-line string.
