---
# Source: digitalhub/charts/seaweedfs/templates/s3-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: seaweedfs-s3
  namespace: default
  labels:
    app.kubernetes.io/name: seaweedfs
    app.kubernetes.io/component: s3
    helm.sh/chart: seaweedfs-4.0.393
    app.kubernetes.io/managed-by: Helm
spec:
  internalTrafficPolicy: Cluster
  ports:
  - name: "swfs-s3"
    port: 8333
    targetPort: 8333
    protocol: TCP
  - name: "metrics"
    port: 9327
    targetPort: 9327
    protocol: TCP
  selector:
    app.kubernetes.io/name: seaweedfs
    app.kubernetes.io/component: s3
