---
# Source: digitalhub/charts/seaweedfs/templates/secret-seaweedfs-db.yaml
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: secret-seaweedfs-db
  namespace: default
  annotations:
    "helm.sh/resource-policy": keep
    "helm.sh/hook": "pre-install"
  labels:
    app.kubernetes.io/name: seaweedfs
    helm.sh/chart: seaweedfs-4.0.393
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: digitalhub
stringData:
  user: "YourSWUser"
  password: "HardCodedPassword"
  # better to random generate and create in DB
  # password: OTkzNzI5ZTRhODI1OTA3MThlMGQ5Y2Mx
