---
# Source: digitalhub/charts/seaweedfs/templates/volume-resize-hook.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: seaweedfs-volume-resize-hook
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-5"
    helm.sh/hook-delete-policy: before-hook-creation
---
# Source: digitalhub/charts/seaweedfs/templates/volume-resize-hook.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: seaweedfs-volume-resize-hook
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-5"
    helm.sh/hook-delete-policy: before-hook-creation
rules:
  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    verbs: ["delete", "get", "list", "watch"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["patch", "get", "list", "watch"]
---
# Source: digitalhub/charts/seaweedfs/templates/volume-resize-hook.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: seaweedfs-volume-resize-hook
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-5"
    helm.sh/hook-delete-policy: before-hook-creation
subjects:
  - kind: ServiceAccount
    name: seaweedfs-volume-resize-hook
roleRef:
  kind: Role
  name: seaweedfs-volume-resize-hook
  apiGroup: rbac.authorization.k8s.io
