---
# Source: digitalhub/charts/seaweedfs/templates/volume-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: seaweedfs-volume
  namespace: default
  labels:
    app.kubernetes.io/name: seaweedfs
    app.kubernetes.io/component: volume
    helm.sh/chart: seaweedfs-4.0.393
    app.kubernetes.io/managed-by: Helm
spec:
  clusterIP: None
  internalTrafficPolicy: Cluster
  ports:
  - name: "swfs-volume"
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: "swfs-volume-18080"
    port: 18080
    targetPort: 18080
    protocol: TCP
  - name: "metrics"
    port: 9327
    targetPort: 9327
    protocol: TCP
  selector:
    app.kubernetes.io/name: seaweedfs
    app.kubernetes.io/component: volume
