---
# Source: aac/templates/secret.yaml
# SPDX-FileCopyrightText: Â© 2025 DSLab - Fondazione Bruno Kessler
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Secret
metadata:
  name: aac-bootstrap-secret
  annotations:
type: Opaque
data:
  bootstrap.yaml: cmVhbG1zOgogIC0gbmFtZTogZGlnaXRhbGh1YgogICAgc2x1ZzogZGlnaXRhbGh1YgogICAgcHVibGljOiB0cnVlCiAgICByb2xlczoKICAgICAgbnVsbAogICAgaWRlbnRpdHlQcm92aWRlcnM6CiAgICAgIC0gYXV0aG9yaXR5OiBpbnRlcm5hbAogICAgICAgIG5hbWU6IGludGVybmFsCiAgICAgICAgcHJvdmlkZXI6IHRlbmFudGlkZW50aXR5CiAgICAgICAgdHlwZTogaWRlbnRpdHkKICAgICAgLSBhdXRob3JpdHk6IHBhc3N3b3JkCiAgICAgICAgbmFtZTogcGFzc3dvcmQKICAgICAgICBwcm92aWRlcjogdGVuYW50cGFzc3dvcmQKICAgICAgICB0eXBlOiBpZGVudGl0eQogICAgY2xpZW50QXBwczoKICAgICAgLSBjbGllbnRJZDogenhpMXdiaHNmM2w5NG0zNGRhYTJtc2F4ZWdvOTIybXEKICAgICAgICB0eXBlOiBvYXV0aDIKICAgICAgICBuYW1lOiBjb3JlCiAgICAgICAgcmVhbG06IGRpZ2l0YWxodWIKICAgICAgICBkZXNjcmlwdGlvbjogCiAgICAgICAgY29uZmlndXJhdGlvbjoKICAgICAgICAgICAgY2xpZW50U2VjcmV0OiB6eGkxd2Joc2YzbDk0bTM0ZGFhMm1zYXhlZ28xNDRmdAogICAgICAgICAgICBhcHBsaWNhdGlvblR5cGU6IHdlYgogICAgICAgICAgICBhdXRoZW50aWNhdGlvbk1ldGhvZHM6CiAgICAgICAgICAgIC0gbm9uZQogICAgICAgICAgICBhdXRob3JpemVkR3JhbnRUeXBlczoKICAgICAgICAgICAgLSBhdXRob3JpemF0aW9uX2NvZGUKICAgICAgICAgICAgLSByZWZyZXNoX3Rva2VuCiAgICAgICAgICAgIGZpcnN0UGFydHk6IHRydWUKICAgICAgICAgICAgaWRUb2tlbkNsYWltczogZmFsc2UKICAgICAgICAgICAgcmVkaXJlY3RVcmlzOgogICAgICAgICAgICAtIGh0dHA6Ly9kaWdpdGFsaHViLWNvcmU6ODA4MC9hdXRoL2NvZGUvb2lkYwogICAgICAgICAgICByZWZyZXNoX3Rva2VuX3JvdGF0aW9uOiB0cnVlCiAgICAgICAgICAgIHN1YmplY3RUeXBlOiBwdWJsaWMKICAgICAgICAgICAgdG9rZW5UeXBlOiBqd3QKICAgICAgICBzY29wZXM6CiAgICAgICAgICAtIGVtYWlsCiAgICAgICAgICAtIHByb2ZpbGUKICAgICAgICAgIC0gb3BlbmlkCiAgICAgICAgICAtIHVzZXIucm9sZXMubWUKICAgICAgICAgIC0gb2ZmbGluZV9hY2Nlc3MKICAgICAgICBwcm92aWRlcnM6CiAgICAgICAgICAtIHRlbmFudHBhc3N3b3JkCiAgICAgICAgYXV0aG9yaXRpZXM6IFsKICAgICAgICAgICAgXQogICAgICAgIHNwYWNlUm9sZXM6IFsKICAgICAgICAgICAgXQogICAgICAgIGhvb2tXZWJVcmxzOiB7CiAgICAgICAgICAgIH0KICAgICAgICByb2xlczogWwogICAgICAgICAgICBdCiAgICB1c2VyczoKICAgICAgLSB1dWlkOiBsZXdvbzN6d3o5eG0ydHU0MGw5dGFkbDM3aHRqcGFnZwogICAgICAgIHVzZXJJZDogdGVuYW50dXNlcmlkCiAgICAgICAgdXNlcm5hbWU6IHRlbmFudAogICAgICAgIGVtYWlsOiB0ZW5hbnRAbG9jYWwuaXQKICAgICAgICB0eXBlOiBhY2NvdW50OmludGVybmFsCiAgICAgICAgYXV0aG9yaXR5OiBpbnRlcm5hbAogICAgICAgIHByb3ZpZGVyOiB0ZW5hbnRpZGVudGl0eQogICAgICAgIG5hbWU6IHRlbmFudAogICAgICAgIHN1cm5hbWU6IHVzZXIKICAgICAgICBjb25maXJtZWQ6IHRydWUKICAgIGNyZWRlbnRpYWxzOgogICAgICAtIHR5cGU6IGNyZWRlbnRpYWxzOnBhc3N3b3JkCiAgICAgICAgYXV0aG9yaXR5OiBwYXNzd29yZAogICAgICAgIHByb3ZpZGVyOiB0ZW5hbnRwYXNzd29yZAogICAgICAgIHVzZXJuYW1lOiB0ZW5hbnQKICAgICAgICB1c2VySWQ6IHRlbmFudHVzZXJpZAogICAgICAgIHBhc3N3b3JkOiBwYXNzd29yZDEyMwogICAgICAgIGlkOiB0ZW5hbnRjcmVkZW50aWFsaWQK
---
# Source: aac/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: aac-digitalhub-core-secret
  annotations:
type: Opaque
data:
  clientid: enhpMXdiaHNmM2w5NG0zNGRhYTJtc2F4ZWdvOTIybXE=
  clientsecret: enhpMXdiaHNmM2w5NG0zNGRhYTJtc2F4ZWdvMTQ0ZnQ=
---
# Source: aac/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: aac-mail-secret
type: Opaque
data:
  jdbc-user: dGVzdEB1c2VyLml0
  jdbc-password: dGVzdFBhc3N3b3Jk
---
# Source: aac/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: aac-admin-secret
type: Opaque
data:
  username: YWRtaW4=
  password: YWRtaW4=
