---
# Source: digitalhub/charts/argo-workflows/templates/controller/artifact-repository-ref-cm.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: artifact-repositories
  namespace: "default"
  labels:
    helm.sh/chart: argo-workflows-0.45.1
    app.kubernetes.io/name: argo-workflows-artifact-repositories
    app.kubernetes.io/instance: digitalhub
    app.kubernetes.io/component: workflow-controller
    app: workflow-controller
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: argo-workflows
  annotations:
    workflows.argoproj.io/default-artifact-repository: artifact-repository
data:
  artifact-repository: |
    archiveLogs: false
    s3:
      accessKeySecret:
        key: accesskey
        name: argo-s3-creds
      bucket: argo
      endpoint: seaweedfs-s3:8333
      insecure: true
      secretKeySecret:
        key: secretkey
        name: argo-s3-creds
