---
# Source: digitalhub/charts/argo-workflows/templates/controller/workflow-controller-crb.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: digitalhub-argo-workflows-workflow-controller-cluster-template
  labels:
    helm.sh/chart: argo-workflows-0.45.1
    app.kubernetes.io/name: argo-workflows-workflow-controller
    app.kubernetes.io/instance: digitalhub
    app.kubernetes.io/component: workflow-controller
    app: workflow-controller
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: argo-workflows
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: digitalhub-argo-workflows-workflow-controller-cluster-template
subjects:
  - kind: ServiceAccount
    name: argo-workflow-controller
    namespace: "default"
---
# Source: digitalhub/charts/argo-workflows/templates/controller/workflow-controller-crb.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding

metadata:
  name: digitalhub-argo-workflows-workflow-controller
  namespace: "default"
  labels:
    helm.sh/chart: argo-workflows-0.45.1
    app.kubernetes.io/name: argo-workflows-workflow-controller
    app.kubernetes.io/instance: digitalhub
    app.kubernetes.io/component: workflow-controller
    app: workflow-controller
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: argo-workflows
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  
  name: digitalhub-argo-workflows-workflow-controller
subjects:
  - kind: ServiceAccount
    name: argo-workflow-controller
    namespace: "default"
