---
# Source: digitalhub/charts/kubeai/templates/rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubeai
  labels:
    helm.sh/chart: kubeai-0.22.1
    app.kubernetes.io/name: kubeai
    app.kubernetes.io/instance: digitalhub
    app.kubernetes.io/version: "v0.22.1"
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kubeai
subjects:
- kind: ServiceAccount
  name: kubeai
