---
# Source: digitalhub/charts/kubeai/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubeai
  labels:
    helm.sh/chart: kubeai-0.22.1
    app.kubernetes.io/name: kubeai
    app.kubernetes.io/instance: digitalhub
    app.kubernetes.io/version: "v0.22.1"
    app.kubernetes.io/managed-by: Helm
automountServiceAccountToken: true
---
# Source: digitalhub/charts/kubeai/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubeai-models
  labels:
    helm.sh/chart: kubeai-0.22.1
    app.kubernetes.io/name: kubeai
    app.kubernetes.io/instance: digitalhub
    app.kubernetes.io/version: "v0.22.1"
    app.kubernetes.io/managed-by: Helm
automountServiceAccountToken: true
