---
# Source: digitalhub/charts/template-controller/templates/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: digitalhub-template-controller-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: digitalhub-template-controller-manager-role
subjects:
  - kind: ServiceAccount
    name: digitalhub-template-controller
    namespace: default
