---
# Source: digitalhub/charts/template-controller/templates/rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: digitalhub-template-controller-leader-election-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: digitalhub-template-controller-leader-election-role
subjects:
  - kind: ServiceAccount
    name: digitalhub-template-controller
    namespace: default
