---
# Source: digitalhub/charts/template-controller/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: digitalhub-template-controller
  labels:
    helm.sh/chart: template-controller-0.2.5
    app.kubernetes.io/name: template-controller
    app.kubernetes.io/instance: digitalhub
    app.kubernetes.io/version: "v0.8.3"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http-prom
      protocol: TCP
      name: http-prom
    - port: 8081
      targetPort: healthz
      protocol: TCP
      name: healthz
  selector:
    app.kubernetes.io/name: template-controller
    app.kubernetes.io/instance: digitalhub
