---
# Source: digitalhub/charts/core/templates/configmap-digitalhub.yaml
# SPDX-FileCopyrightText: Â© 2025 DSLab - Fondazione Bruno Kessler
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ConfigMap
metadata:
  name: digitalhub-common-env
data:
  S3_BUCKET: datalake
  AWS_ENDPOINT_URL: "http://seaweedfs-s3:8333"
  DB_HOST: database-postgres-cluster
  DB_PORT: "5432"
  DB_DATABASE: digitalhub
  DHCORE_ENDPOINT: http://digitalhub-core:8080
  DHCORE_ISSUER: http://digitalhub-core:8080
  DHCORE_DEFAULT_FILES_STORE: s3://datalake
  AWS_REGION: us-east-1
