---
# Source: digitalhub/charts/core/templates/secret.yaml
# SPDX-FileCopyrightText: Â© 2025 DSLab - Fondazione Bruno Kessler
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Secret
metadata:
  name: core-auth-creds
type: Opaque
data:
  clientId: bTA0YmZibWQwM204c2Y0dTl1Y3o1NHRp
  clientSecret: OXJiNTIxNXowYXFkN2ZhZHp4dW95cWUz
