name: Lint and Test Charts

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read 

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.0
      - name: Add dependency chart repos and Update Dependencies
        run: |
          helm repo add postgres-operator https://opensource.zalando.com/postgres-operator/charts/postgres-operator
          helm repo add argo https://argoproj.github.io/argo-helm
          helm repo add digitalhub-charts https://scc-digitalhub.github.io/digitalhub/ 
          helm repo add docker-registry https://twuni.github.io/docker-registry.helm
          helm repo add seaweedfs https://seaweedfs.github.io/seaweedfs/helm
          helm repo add kluctl https://kluctl.github.io/charts
          helm repo add kubeai https://www.kubeai.org
          helm dependency update ./charts/aac
          helm dependency update ./charts/digitalhub

      - name: Run Helm Lint and Template Checks
        run: |
          helm lint ./charts/aac
          helm lint ./charts/core
          helm template my-release ./charts/aac
          helm template my-release ./charts/core 
        
      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.7.0

      - name: Create kind cluster
        uses: helm/kind-action@v1.12.0

      - name: Run chart-testing (install)
        run: ct install \ 
                --release-name digitalhub \
                --charts ./charts/digitalhub \
                --charts ./charts/aac \
                --set-files values-demo=./charts/digitalhub/values-demo.yaml
      - name: Chart-test
        run: helm test digitalhub --timeout 60m
             